---
title: "Sobre este site"
editor: source
---

Este é um site experimental do grupo de estudos e pesquisas em Ecologia de Rios do Semiárido (GERSA), que é vinculado ao Laboratório de Ecologia do campus V da Universidade Estadual da Paraíba.

O site é uma plataforma criada com o objetivo de apresentar este grupo de estudos e pesquisas, ao mesmo tempo explorando diferentes conceitos e técnicas utilizados na análise de dados em Ecologia, associados a disciplina de Ecologia Numérica do Curso de Bacharelado em Ciências Biológicas da UEPB.

É importante destacar que os exemplos apresentados no site podem conter imprecisões ou códigos demasiado extensos (aparentemente desnecessários para um ecólogo e programador de R mais experiente), mas isso é proposital, pois a finalidade é oferecer um material didático para os alunos, que possa facilitar a compreensão dos conceitos abordados nas aulas e estudos de Ecologia. Dessa forma, o site é uma ferramenta complementar às aulas presenciais e as pesquisas realizadas pelo grupo, buscando fornecer exemplos práticos e didáticos para estudantes de Ecologia.

Como mencionado, a finalidade é didatica e de apresentar os temas seguindo passo-a-passoa e contextualizando com dados ecológicos reais. Por isso, além das informações sobre o conteúdo do site experimental deste grupo, é importante destacar que qualquer erro ou problema relacionado ao site podem ser reportados ao responsável através do email: [elviomedeiros\@servidor.uepb.edu.br](elviomedeiros@servidor.uepb.edu.br)

É fundamental que os usuários do site compreendam que plágio e outras formas de má conduta acadêmica são inaceitáveis e podem ter sérias consequências. O responsável pelo site se compromete a remover qualquer conteúdo ofensivo ou sem a devida fonte consultada, que possa ter sido publicado erroneamente ou por engano.
